extensions:
  - name: python
    file_extension: py
    source_lib: /Users/user/Documents/zenoh-flow-lab/zenoh-flow-python/target/release/libpy_source.dylib
    sink_lib: /Users/user/Documents/zenoh-flow-lab/zenoh-flow-python/target/release/libpy_sink.dylib
    operator_lib: /Users/user/Documents/zenoh-flow-lab/zenoh-flow-python/target/release/libpy_op.dylib
    config_lib_key: python-script